output_dir: /project/6050429/sgelinas/salt/gnn-plots/output/GN3ej-combined-extLabels-fold0

samples: &samples
  New samples:
    input_dir: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-combined-extLabels-fold0-classdict_20250606-T150049/ckpts/lifetime'
    label: 'New samples' #'New samples - weights'
    df_name: jets
  #New no weights:
  #  input_dir: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-combined-extLabels-fold0_20250602-T183213/ckpts/lifetime'
  #  label: 'New samples - no weights'
  #  df_name: jets
  Old samples:
    input_dir: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0-classdict_20250610-T130836/ckpts/lifetime'
    label: 'Old samples' #'Old samples - weights'
    df_name: jets
  #Old no weights:
  #  input_dir: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0_20250610-T224142/ckpts/lifetime'
  #  label: 'Old samples - no weights'
  #  df_name: jets

style: &style
  figsize: !!python/tuple [6, 4.5]  # figure sizes in this range work best
  label_fontsize: 13
  fontsize: 13
  atlas_first_tag: "Simulation Internal"
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV, $51.8$ fb$^{-1}$"
  atlas_fontsize: 14
  y_scale: 1.4
  grid: False

plots:
  eff_vs_lifetime:
    class: plotter.plot_classes.signal_eff_plot.SignalEffPlotBase
    samples: *samples
    target_label: isDisplaced
    cut_value: 0.98
    file_name: output/final-student-presentation/lifetime_eff.png # output
    style:
      <<: *style
      n_ratio_panels: 0
      ylabel: "EJ tagging efficiency for $p_\\mathrm{EJ} > 0.98$"
      xlabel: "Lifetime [mm]"
