output_dir: /project/6050429/sgelinas/salt/gnn-plots/output/GN3ej-fold0

samples: &samples
  #four:
   # path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-fold0_20250529-T124301/ckpts/epoch=008-val_loss=0.02599__test_pp_output_val.h5'
   # label: 'New samples combined - no weights'
   # reference: False
   # df_name: jets
   # flip_jet_labels: True
  three:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-combined-extLabels-fold0-classdict_20250606-T150049/ckpts/epoch=007-val_loss=0.02522__test_pp_output_val.h5'
    label: 'New samples, new labels' # 'New samples fold 0 - weights
    reference: False
    df_name: jets
    flip_jet_labels: False
  #two:
   # path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-combined-extLabels-fold0_20250602-T183213/ckpts/epoch=005-val_loss=0.02643__test_pp_output_val.h5'
   # label: 'New samples fold 0 - no weights'
   # reference: False
   # df_name: jets
   # flip_jet_labels: False
  six:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0-classdict_20250610-T130836/ckpts/epoch=011-val_loss=0.00779__test_pp_output_val.h5'
    label: 'Old samples, new labels' #'Old samples - weights'
    reference: False
    df_name: jets
    flip_jet_labels: False
  #five:
  #  path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0_20250610-T224142/ckpts/epoch=009-val_loss=0.00795__test_pp_output_val.h5'
  #  label: 'Old samples - no weights'
  #  reference: False
  #  df_name: jets
  #  flip_jet_labels: False
  one:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-fold0_20250521-T171616/ckpts/epoch=010-val_loss=0.02672__test_pp_output_val.h5'
    label: 'Old samples, old labels' # 'Nominal'
    reference: True
    df_name: jets
    flip_jet_labels: False

style: &style
  figsize: !!python/tuple [9, 5.5] #[8, 4.5]  # figure sizes in this range work best
  label_fontsize: 13
  fontsize: 13
  atlas_first_tag: "Simulation Internal"
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV, $51.8$ fb$^{-1}$, $p_{EJ} > 0.98$"
  atlas_fontsize: 14
  ymin: 1
  y_scale: 0.9
  grid: False

plots:
  roc:
    class: plotter.plot_classes.roc_plot.RocPlotBase
    samples: *samples
    file_name: output/final-student-presentation/roc_weights_extLabels_all.png
    target_label: isDisplaced
    tagger_output: GN2ej_pdispjet
    range: !!python/tuple [0.95, 1, 100]
    show_cuts: True  # choose whether to display your desired cuts
    leg_inside: False
    leg_fontsize: 13
    reference_label: "nominal"
    cut_values: [0.98]  # or None
    style:
      <<: *style
      n_ratio_panels: 0
      ylabel: "Background rejection "
      xlabel: "EJ tagging efficiency "
      y_scale: 1.3