output_dir: output

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [6, 6]
  use_atlas_tag: False
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  conf_mat:
    class: plotter.plot_classes.confusion_matrix_extLabels_plot.ConfMatPlotBase
    samples:
      path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0-classdict_20250610-T130836/ckpts/epoch=011-val_loss=0.00779__test_pp_output_val.h5'
      label: 'GN3ej'
      df_name: tracks # two options are tracks, jets
    file_name: output/GN3ej-oldSamples-extLabels-fold0/confusion_weights.png
    style:
      <<: *style
      xlabel: GN3ej prediction
      ylabel: Truth labels
      figsize: !!python/tuple [8,8]
      show_entries: True
      text_color_threshold: 0.6
      colormap: GnBu
      cbar_label: ""
