output_dir: output

samples: &samples
  five:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0-classdict_20250610-T130836/ckpts/epoch=011-val_loss=0.00779__test_pp_output_val.h5'
    label: 'Trained on v1, evaluated on v1'
  four:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-oldSamples-extLabels-fold0-classdict_20250610-T130836/ckpts/epoch=011-val_loss=0.00779__test_pp_output_val_new.h5'
    label: 'Trained on v1, evaluated on v2'
  three:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-combined-extLabels-fold0-classdict_20250606-T150049/ckpts/epoch=007-val_loss=0.02522__test_pp_output_val_old.h5'
    label: 'Trained on v2, evaluated on v1'
  two:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-combined-extLabels-fold0-classdict_20250606-T150049/ckpts/epoch=007-val_loss=0.02522__test_pp_output_val.h5'
    label: 'Trained on v2, evaluated on v2'
  one:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-fold0_20250521-T171616/ckpts/epoch=010-val_loss=0.02672__test_pp_output_val.h5'
    label: 'Nominal (v0)'

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [6, 6]
  use_atlas_tag: True
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  jetpt_perf:
    class: plotter.plot_classes.jetpt_perf_plot.JetPtPerfPlotBase
    samples: *samples
    sig_eff_filename: output/EJ_eff_vs_jetpT.png
    bkg_rej_filename: output/QCD_rej_vs_jetpT.png
    working_point: 0.98
    binedges: [0.2,0.3,0.4,0.5,0.6,0.8,1.2,2.25]  # in TeV
    sig_eff_leg_loc: lower right
    bkg_rej_leg_loc: upper left
    style:
      <<: *style
      grid: True
      figsize: !!python/tuple [7,5]
      y_scale: 1.0
      atlas_tag_outside: True