output_dir: output

samples: &samples
  GN2ej:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-fold0_20250521-T174316/ckpts/epoch=009-val_loss=0.02690__test_pp_output_val.h5'
    label: 'two parts'
    reference: True
    df_name: jets
  GN2ej_noPt:
    path: '/project/def-mdanning/sgelinas/salt/salt/logs/GN3ej-fold0_20250521-T171616/ckpts/epoch=010-val_loss=0.02672__test_pp_output_val.h5'
    label: 'one part'
    reference: False
    df_name: jets
  #GN2ej_4:
    #path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_4_20240611-T092747/ckpts/epoch=012-val_loss=0.02329__test_pp_output_val.h5'
    #label: 'mc23-fold0 - 4 layers'
    #reference: False
    #df_name: jets
  #GN2ej_3:
   # path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_3_20240610-T114657/ckpts/epoch=009-val_loss=0.02301__test_pp_output_val.h5'
   # label: 'mc23-fold0 - 3 layers'
   # reference: False
   # df_name: jets
  #GN2ej_2:
   # path: '/project/def-mdanning/rhall02/salt/salt/logs/GN2ej_2_20240611-T092747/ckpts/epoch=012-val_loss=0.02351__test_pp_output_val.h5'
   # label: 'mc23-fold0 - 2 layers'
   # reference: False
   # df_name: jets

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [6.5, 6]
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0

plots:
  roc:
    class: plotter.plot_classes.roc_plot.RocPlotBase
    samples: *samples
    file_name: output/GN3ej-fold0/roc-compare.png
    target_label: isDisplaced
    tagger_output: GN2ej_pdispjet
    range: !!python/tuple [0.95, 1, 100]
    show_cuts: True
    cut_values: [0.98]  # or None
    reference_label: "nominal"
    style:
      <<: *style
      n_ratio_panels: 1
      ylabel: "QCD rejection"
      xlabel: "EJ efficiency"
      y_scale: 1.4